sudo: required
services:
  - docker

before_install:
  - docker build -t dc13ml/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run dc13ml/react-test npm test -- --coverage

after_success:
  - docker build -t dc13ml/multi-client ./client
  - docker build -t dc13ml/multi-nginx ./nginx
  - docker build -t dc13ml/multi-server ./server
  - docker build -t dc13ml/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push dc13ml/multi-client
  - docker push dc13ml/multi-nginx
  - docker push dc13ml/multi-client
  - docker push dc13ml/multi-server
  - docker push dc13ml/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-741344268822
  bucket_path: docker_multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY

