sudo: required
services:
  - docker

before_install:
  - docker build -t dc13ml/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run dc13ml/react-test npm test -- --coverage

after_success:
  - docker build -t dc13ml/multi-client ./client
  - docker build -t dc13ml/multi-nginx ./nginx
  - docker build -t dc13ml/multi-server ./server
  - docker build -t dc13ml/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push dc13ml/multi-client
  - docker push dc13ml/multi-nginx
  - docker push dc13ml/multi-client
  - docker push dc13ml/multi-server
  - docker push dc13ml/multi-worker

